### ISSUE TITLE
Offline Keys Option

### ISSUE THREAD

**Issue by brethvoice** [StardustCollective/stargazer-wallet-ext#119]
Does the Stargazer Wallet ecosystem give explicit guidance about how to extract and explicitly store one's token(s) elsewhere to keep them out of reach of hackers (hardware wallet, NordLocker secured with Yubikey, etc.)?

**Comment by AlexBrandes** [comment]
Hi @brethvoice,
I'd suggest you ask these kinds of questions on Telegram. The community there is very active and can help point you in the right direction. 

Stargazer support: https://t.me/StardustSupport
Constellation community: https://t.me/constellationcommunity
