### ISSUE TITLE
Approve spend screen shows no error when user has no ETH for gas

### ISSUE THREAD

**Issue by AlexBrandes** [StardustCollective/stargazer-wallet-ext#185]
Several users have reported that clicking the “confirm” button on the approve spend screen “does nothing”. In each of these cases the user has no ETH in their wallet for gas fees but it appears we don’t show any sort of error message. A proactive error message in this case (all approve txns will require gas) would be the ideal solution.

**Comment by AleemRehman** [comment]
Hi @AlexBrandes, I can take a look at this!
