### ISSUE TITLE
Wallet locks itself frequently when clicking away from the extension

### ISSUE THREAD

**Issue by StrannikAD** [StardustCollective/stargazer-wallet-ext#35]
**Issue:**

The wallet locks itself when clicking away on a new browser/tab window. This happens intermittently - sometimes it doesn't lock away right away, but frequently just one click away will cause the wallet to lock up.

**Expected behaviour:**
The self lock mechanism should be consistent and ideally based on a timed function - e.g >1min of inactivity causes the wallet to lock itself.

**Comment by devneser** [comment]
It's resolved by updating `manifest.json` @StrannikAD
