### ISSUE TITLE
Cannot get local development version to run

### ISSUE THREAD

**Issue by matiassequeira** [StardustCollective/stargazer-wallet-ext#391]
Hi, I'm trying to get the extension up and running in my local dev env. I'm using Node 16 and did a `yarn install` and `yarn run dev:chrome`. 

I loaded the extension in Chrome as usual and the extension is blank as shown in the picture below:

![image](https://user-images.githubusercontent.com/14353293/207898886-9add0852-0b3e-4885-be17-87aea9368b29.png)

I attempted using both MacOs and Ubuntu and got the same result

**Comment by AlexBrandes** [comment]
Hi @matiassequeira - 
You'll need to copy the .env.example in the root directory to a .env file and fill in the environment variables with your own API keys. There are a fairly large number of them required now for supporting multiple chains and their associated block explorers, RPC endpoints, etc. 

**Here are the required ones:** 
ETHERSCAN_API_KEY (required - ETH transaction history)
POLYGONSCAN_API_KEY (required - Polygon transaction history)
BSCSCAN_API_KEY (required - BSC transaction history)
SNOWTRACE_API_KEY (required - Avalanche transaction history)
COINGECKO_API_KEY (required - pricing information)
QUICKNODE_ETHEREUM_MAINNET (required - any ETH mainnet RPC endpoint)
QUICKNODE_ETHEREUM_GOERLI (required - any ETH goerli RPC endpoint)
QUICKNODE_POLYGON_MAINNET (required - any Polygon mainnet RPC endpoint)
QUICKNODE_POLYGON_TESTNET (required - any Polygon testnet RPC endpoint)
QUICKNODE_BSC_MAINNET (required - any BSC mainnet RPC endpoint)
QUICKNODE_BSC_TESTNET (required - any BSC testnet RPC endpoint)
QUICKNODE_AVALANCHE_MAINNET (required - any Avalanche mainnet RPC endpoint)
QUICKNODE_AVALANCHE_TESTNET (required - any Avalanche testnet RPC endpoint)

**Here are the optional ones:**
TEST_PRIVATE_KEY (optional - required to run E2E tests)
OPENSEA_API_KEY (optional - rate limited without the key)
SENTRY_DNS (optional - analytics/crash reports)
STARGAZER_PROVIDERS_BASE_URL (optional - only required for buy flow)
STARGAZER_PROVIDERS_BASE_URL_PROD (optional - only required for buy flow)
STARGAZER_API_KEY (optional - only required for buy flow)

**Comment by matiassequeira** [comment]
Hi @AlexBrandes thanks for your response. I was wondering if the wallet expects just QuickNode RPC endpoints? Because its free tier allows just one endpoint per account. In other words, do you know if I can use another provider?

**Comment by AlexBrandes** [comment]
@matiassequeira You should be able to use any RPC endpoint. It gets passed into the ethers library as a generic JsonRpcProvider.

**Comment by AlexBrandes** [comment]
Closing this one for now - feel free to open another issue if you need more help.
